#!/usr/bin/env bash
# install.sh — interactive first-time setup for this NixOS rice.
#
# Run as root (or with sudo) from /etc/nixos after cloning the repo:
#   sudo git clone https://github.com/SupremeTitan48/personal-nix-rice /etc/nixos
#   cd /etc/nixos && sudo bash install.sh
#
# What this script does:
#   1. Collects your personal settings interactively
#   2. Writes user-config.nix with your answers
#   3. Generates hosts/desktop/hardware.nix for this machine
#   4. Creates ~/wallpapers/ and reminds you to add a wallpaper
#   5. Runs nixos-rebuild switch to activate the config
set -euo pipefail

# ── helpers ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}${BOLD}==> ${RESET}${BOLD}$*${RESET}"; }
success() { echo -e "${GREEN}${BOLD} ✓  $*${RESET}"; }
warn()    { echo -e "${YELLOW}${BOLD} !  $*${RESET}"; }
die()     { echo -e "${RED}${BOLD}ERR $*${RESET}" >&2; exit 1; }

ask() {
  # ask <var_name> <prompt> [default]
  local var="$1" prompt="$2" default="${3:-}"
  local display_default=""
  [[ -n "$default" ]] && display_default=" [${default}]"
  read -rp "$(echo -e "${BOLD}${prompt}${display_default}: ${RESET}")" value
  value="${value:-$default}"
  [[ -z "$value" ]] && die "'${prompt}' cannot be empty."
  printf -v "$var" '%s' "$value"
}

# ── pre-flight ─────────────────────────────────────────────────────────────────
[[ $EUID -ne 0 ]] && die "Run this script as root: sudo bash install.sh"

if ! command -v nixos-rebuild &>/dev/null; then
  die "This script must run on NixOS. nixos-rebuild not found."
fi

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO_DIR"

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════════════╗${RESET}"
echo -e "${BOLD}║       NixOS Rice — First-time Setup              ║${RESET}"
echo -e "${BOLD}╚══════════════════════════════════════════════════╝${RESET}"
echo ""
echo "This will walk you through the required settings and then build"
echo "your system. You can re-run it at any time to change values."
echo ""

# ── gather settings ────────────────────────────────────────────────────────────
info "Identity"
ask USERNAME   "Linux username (no spaces, lowercase)"      "$(logname 2>/dev/null || echo 'user')"
ask GIT_NAME   "Your full name (for git)"                   ""
ask GIT_EMAIL  "Your email (for git)"                       ""

echo ""
info "Locale"
DEFAULT_TZ="$(timedatectl show --property=Timezone --value 2>/dev/null || echo 'America/Chicago')"
ask TIMEZONE   "Timezone (timedatectl list-timezones)"      "$DEFAULT_TZ"

echo ""
info "Night light — blue-light filter (find coords at https://latlong.net)"
ask LAT        "Latitude  (e.g. 41.8 for Chicago)"         "41.8"
ask LON        "Longitude (e.g. -87.6 for Chicago — west is negative)" "-87.6"

echo ""
info "Display"
echo "  We cannot detect your monitor connector until after the first boot."
echo "  The default below works for single-monitor DisplayPort setups."
echo "  After booting, run: hyprctl monitors  — then update user-config.nix."
ask MONITOR    "Monitor string (CONNECTOR,WIDTHxHEIGHT@REFRESH,POSx,SCALE)" "DP-1,2560x1440@240,0x0,1"

echo ""
info "GPU"
echo "  NVIDIA open kernel module:"
echo "    true  → RTX 30xx (Ampere) and newer — best Wayland performance"
echo "    false → GTX / RTX 20xx / older — uses the proprietary module"
ask NVIDIA_OPEN "Use open kernel module? (true/false)" "true"
[[ "$NVIDIA_OPEN" != "true" && "$NVIDIA_OPEN" != "false" ]] && \
  die "nvidiaOpen must be 'true' or 'false'."

echo ""
info "Continuous deployment (optional)"
echo "  When set, a systemd timer pulls from your GitHub repo every hour"
echo "  and rebuilds the system automatically."
echo "  Leave blank to disable auto-upgrade."
ask REPO_URL "GitHub repo URL (e.g. github:owner/repo or leave blank)" \
  "github:SupremeTitan48/personal-nix-rice"

# ── write user-config.nix ──────────────────────────────────────────────────────
echo ""
info "Writing user-config.nix..."

cat > "${REPO_DIR}/user-config.nix" <<EOF
# user-config.nix — generated by install.sh on $(date -u +%Y-%m-%d).
# Edit manually or re-run install.sh to change any value.
{
  username    = "${USERNAME}";
  gitName     = "${GIT_NAME}";
  gitEmail    = "${GIT_EMAIL}";
  timezone    = "${TIMEZONE}";
  latitude    = "${LAT}";
  longitude   = "${LON}";
  monitor     = "${MONITOR}";
  nvidiaOpen  = ${NVIDIA_OPEN};
  repoUrl     = "${REPO_URL}";
  quickshellDev = true;
}
EOF
success "user-config.nix written."

# ── generate hardware config ───────────────────────────────────────────────────
info "Generating hardware configuration for this machine..."
nixos-generate-config --show-hardware-config \
  > "${REPO_DIR}/hosts/desktop/hardware.nix"
success "hosts/desktop/hardware.nix generated."

# ── wallpaper directory ────────────────────────────────────────────────────────
WALLPAPER_DIR="/home/${USERNAME}/wallpapers"
mkdir -p "$WALLPAPER_DIR"

if [[ ! -f "${WALLPAPER_DIR}/default.jpg" && ! -f "${WALLPAPER_DIR}/default.png" ]]; then
  warn "No wallpaper found at ${WALLPAPER_DIR}/default.jpg"
  warn "Add a dark JPEG or PNG there before logging into Hyprland:"
  warn "  cp /path/to/your/wallpaper.jpg ${WALLPAPER_DIR}/default.jpg"
  echo ""
  read -rp "$(echo -e "${BOLD}Press Enter to continue without a wallpaper (stub colors will be used), or Ctrl-C to add one first...${RESET}")"
fi

# ── generate flake.lock if missing ────────────────────────────────────────────
if [[ ! -f "${REPO_DIR}/flake.lock" ]]; then
  info "Generating flake.lock (pinning all inputs)..."
  nix flake update --flake "$REPO_DIR"
  success "flake.lock created."
fi

# ── build ─────────────────────────────────────────────────────────────────────
echo ""
info "Building NixOS configuration — this may take a while on first run..."
echo "  (Subsequent builds are much faster thanks to the Nix store cache)"
echo ""

nixos-rebuild switch --flake "${REPO_DIR}#desktop"

echo ""
echo -e "${GREEN}${BOLD}╔══════════════════════════════════════════════════╗${RESET}"
echo -e "${GREEN}${BOLD}║   Setup complete! Reboot and select Hyprland.    ║${RESET}"
echo -e "${GREEN}${BOLD}╚══════════════════════════════════════════════════╝${RESET}"
echo ""
echo "  Next steps:"
echo "  1. Reboot: sudo reboot"
echo "  2. Select 'Hyprland' in the SDDM login screen"
echo "  3. Press Super+W to open the wallpaper picker"
echo "  4. If the monitor connector is wrong, run: hyprctl monitors"
echo "     Update the 'monitor' field in user-config.nix and rebuild:"
echo "     sudo nixos-rebuild switch --flake /etc/nixos#desktop"
echo ""
